#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

# Start command line interface for application
require Mojolicious::Commands;
require Batware;

my $commands = Mojolicious::Commands->new(app => Batware->new);
push @{$commands->namespaces}, 'Batware::Command';
$commands->run(@ARGV);
